### ISSUE TITLE
[Feature Request] Allow us to add x-callback-urls

### ISSUE THREAD

**Issue by aizoule** [joshwolff1/spontit_api#1]
I was going to use that service for Apple's Shortcuts app. But it seems doesn't support the x-callback-urls.

`>>> resource.push("simple notification", link="shortcuts://gallery")
{'Error': 'The URL you entered is not valid.'}`

**Comment by joshwolff1** [comment]
Hi Aizoule! 

I will try to add this soon and get back to you. If I have any questions, I will add them here.

Thank you,
Josh

**Comment by joshwolff1** [comment]
Hi Aizoule,

Thank you for your patience.

We have updated the app and the PyPi package. You will need spontit **v1.0.4** (pip install spontit --upgrade) and you will need the Spontit iOS app **v6.0.1**.

You can add a deep link from the app or from code.

To accomplish this from code, do the following:

`resource.push("simple notification", ios_deep_link="shortcuts://gallery")`

I have tested this and it works. If you have any issues with it, I will reopen this.

Please note that we do not support Android deep links at the moment, but if you need this for some reason, please make a new request.

Please let us know if you have any new feature requests, please rate us 5 stars on the App Store, and have a great day!

Cheers,
Josh
