### ISSUE TITLE
White page on android App

### ISSUE THREAD

**Issue by Dam-35** [joshwolff1/spontit_api#3]
Hi,

I know Spontit is focused on iOS but I just wanted to inform that on Android, App only displays a white page.
It seems app tries to reach www.spontit.me and does not follow the redirection to spontit.com.

Thanks again !

**Comment by joshwolff1** [comment]
Hi Dam-35,

Although we once used www.spontit.me, we are no longer connecting the two domains.

Are you typing spontit.me in the browser or are we linking to it somewhere / in some way?

If we are linking to it, can you point me to where we are doing so and I will fix it?

Thank you for pointing this out,
Josh

**Comment by Dam-35** [comment]
Hi Josh

I'm not sure of the expected behaviour in Android but here are the steps I follow : 

1. Download the app through Play store
1. Launch the App
1. Then only a white screen is displayed (browser in full screen i guess ?)
1. if I wait more than 30 secs and refresh the page, I sometimes have a message "www.spontit.me does not respond - ERR_CONNECTION_TIMED_OUT" displayed

I Hope this helps.

I have this same behaviour on a Samsung running Android 9 and a Huawei running Android 8.

**Comment by joshwolff1** [comment]
Oh, wow, of course! I know the issue, but it might take a few days to fix. 

Thank you very much for pointing this out.

Here is the cause: Our Android app is a PWA, which is a fancy name for "we uploaded our website to the Google Play Store". I apparently forgot to change the website on the Play Store after we disconnected spontit.me. I will do so now, but it might take a few days. In the meantime, visiting spontit.com in the browser of your Android should give you the expected functionality.

I created a temporary fix, and the PWA (version on the Play Store) should work now, but I recommend using spontit.com in the browser for uninterrupted service.

I apologize for the inconvenience and I will let you know here when it is resolved.

**Comment by Dam-35** [comment]
Great, thanks for your quick reply and action.

Indeed, using spontit.com provide expected feature so it's perfect for now and suits our needs.

Just FYI, through the PWA it seems Sign in with Google is blocked as spontit.me is not an authorized domain (there's a pop-in when you tap on log in with google button)

**Comment by joshwolff1** [comment]
Sure, I'm happy to help

Glad to hear spontit.com is working

I just fixed the spontit.me log-in issue you mentioned - thank you for pointing this out as well

**Comment by joshwolff1** [comment]
Hi Dam-35,

In order to change the domain and resolve the issue, I had to release a new app.

You can get it here: https://play.google.com/store/apps/details?id=xyz.appmaker.nqratw

I will remove the other from the Play Store. Thank you for your patience. If you have a chance, we would definitely appreciate a review on the Play Store and the App Store.

Thanks again for reporting this and feel free to open up a new issue as things arise,
Josh
